using System.Globalization;
using System.Text;

namespace Imp.Wiki;

// Step 6 of project/wiki-plan.md. Walks <repoRoot>/<wikiDir>/**/*.md, parses
// each page's frontmatter, and emits the index markdown for wiki/README.md.
//
// Pure determinism: no model calls, no executor. The index is a roll-up of
// page frontmatter — the page bodies aren't read. To re-render the index
// after a regen, callers walk the wiki dir and pass the result to Render.

public sealed record WikiIndexEntry(
    string SourcePath,
    string PageRelativePath,    // path inside wikiDir (e.g. "src/Foo.md")
    WikiPageFrontmatter Frontmatter);

public sealed record WikiIndexSummary(
    int TotalPages,
    int Generated,
    int Oversized,
    int Failed,
    int Other);

public static class WikiIndexRenderer
{
    public static (string Markdown, WikiIndexSummary Summary) RenderFromDirectory(
        string repoRoot,
        string wikiDir,
        DateTimeOffset renderedAt,
        string? modelBody = null)
    {
        var entries = LoadEntries(repoRoot, wikiDir);
        var summary = SummariseEntries(entries);
        return (Render(entries, summary, renderedAt, modelBody), summary);
    }

    public static IReadOnlyList<WikiIndexEntry> LoadEntries(string repoRoot, string wikiDir)
    {
        var wikiAbs = Path.Combine(repoRoot, wikiDir);
        if (!Directory.Exists(wikiAbs)) return Array.Empty<WikiIndexEntry>();

        var entries = new List<WikiIndexEntry>();
        foreach (var file in Directory.EnumerateFiles(wikiAbs, "*.md", SearchOption.AllDirectories))
        {
            var relative = Path.GetRelativePath(wikiAbs, file).Replace('\\', '/');
            // The index itself is the README; skip so a regen doesn't list itself.
            if (string.Equals(relative, "README.md", StringComparison.OrdinalIgnoreCase)) continue;

            var fm = WikiPageFrontmatterReader.Parse(file);
            if (fm is null) continue;
            // Skip repo-root entries — they collide with the index slot. The
            // orchestrator shouldn't write them, but defend anyway.
            if (string.IsNullOrEmpty(fm.SourcePath)) continue;

            entries.Add(new WikiIndexEntry(
                SourcePath: fm.SourcePath!,
                PageRelativePath: relative,
                Frontmatter: fm));
        }

        entries.Sort((a, b) =>
        {
            var byPath = string.Compare(a.SourcePath, b.SourcePath, StringComparison.Ordinal);
            return byPath != 0 ? byPath : string.Compare(a.PageRelativePath, b.PageRelativePath, StringComparison.Ordinal);
        });
        return entries;
    }

    public static WikiIndexSummary SummariseEntries(IReadOnlyList<WikiIndexEntry> entries)
    {
        int g = 0, o = 0, f = 0, x = 0;
        foreach (var e in entries)
        {
            switch (e.Frontmatter.Status)
            {
                case "generated": g++; break;
                case "oversized": o++; break;
                case "failed": f++; break;
                default: x++; break;
            }
        }
        return new WikiIndexSummary(entries.Count, g, o, f, x);
    }

    public static string Render(
        IReadOnlyList<WikiIndexEntry> entries,
        WikiIndexSummary summary,
        DateTimeOffset renderedAt,
        string? modelBody = null)
    {
        var sb = new StringBuilder();
        sb.Append("# imp wiki\n\n");

        if (entries.Count == 0)
        {
            sb.Append("> _Pages mirror the source tree at `wiki/<path>.md`. Each page is a citation-anchored survey of one directory, generated by `imp wiki`. Run again to refresh stale pages._\n\n");
            sb.Append("_No wiki pages have been generated yet. Run `imp wiki` to populate this index._\n");
            return sb.ToString();
        }

        if (!string.IsNullOrWhiteSpace(modelBody))
        {
            sb.Append(modelBody!.Trim()).Append("\n\n");
        }
        else
        {
            sb.Append("> _Pages mirror the source tree at `wiki/<path>.md`. Each page is a citation-anchored survey of one directory, generated by `imp wiki`. Run again to refresh stale pages._\n\n");
        }

        sb.Append("## Pages\n\n");
        sb.Append("| Source path | Status | Generated | Summary |\n");
        sb.Append("|---|---|---|---|\n");
        foreach (var entry in entries)
        {
            var fm = entry.Frontmatter;
            var status = fm.Status ?? "unknown";
            var generated = ShortDate(fm.GeneratedAt);
            var summaryText = SummaryFor(fm);

            // Cluster pages display "<sourcePath> / <slug>" so multiple
            // clusters of the same parent dir don't all read as the same row.
            var displayPath = string.IsNullOrEmpty(fm.ClusterSlug)
                ? entry.SourcePath
                : $"{entry.SourcePath} / {fm.ClusterSlug}";

            sb.Append("| [")
              .Append(EscapeTableCell(displayPath))
              .Append("](")
              .Append(entry.PageRelativePath)
              .Append(") | ").Append(EscapeTableCell(status))
              .Append(" | ").Append(EscapeTableCell(generated))
              .Append(" | ").Append(EscapeTableCell(summaryText))
              .Append(" |\n");
        }

        sb.Append('\n').Append("---\n\n");
        sb.Append("_Regenerated ").Append(renderedAt.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ssZ", CultureInfo.InvariantCulture));
        sb.Append(". ").Append(summary.TotalPages).Append(" page").Append(summary.TotalPages == 1 ? "" : "s")
          .Append(": ").Append(summary.Generated).Append(" generated, ")
          .Append(summary.Oversized).Append(" oversized, ")
          .Append(summary.Failed).Append(" failed");
        if (summary.Other > 0)
            sb.Append(", ").Append(summary.Other).Append(" unknown");
        sb.Append("._\n");

        return sb.ToString();
    }

    static string SummaryFor(WikiPageFrontmatter fm)
    {
        if (!string.IsNullOrWhiteSpace(fm.SynthesisSummary))
            return fm.SynthesisSummary!;
        return fm.Status switch
        {
            "oversized" => $"_Stub: {fm.SourceBytes ?? 0} bytes > {fm.Threshold ?? 0} threshold._",
            "failed" => $"_Failed: {fm.Error ?? "unknown error"}._",
            _ => "—",
        };
    }

    static string ShortDate(string? generatedAt)
    {
        if (string.IsNullOrEmpty(generatedAt)) return "—";
        if (DateTimeOffset.TryParse(generatedAt, CultureInfo.InvariantCulture,
                DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal, out var dt))
            return dt.UtcDateTime.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        return generatedAt;
    }

    // Pipes break markdown tables; backslash-escape any in cell content.
    // Newlines are collapsed to spaces — synthesis_summary already comes
    // pre-collapsed from the page renderer, but errors and paths could carry
    // them.
    static string EscapeTableCell(string value)
    {
        return value.Replace("\\", "\\\\").Replace("|", "\\|").Replace("\n", " ").Replace("\r", "");
    }
}
